package com.isartdigital.sokoban.game.level;

/**
 * @author DELCENSERIE Kalvin
 */
enum Blocks {
	GROUND;
	PLAYER;
	BOX;
	WALL;
	RAILVERTICAL;
	RAILHORIZONTAL;
	TURNINGRAILTOPLEFT;
	TURNINGRAILTOPRIGHT;
	TURNINGRAILBOTTOMLEFT;
	TURNINGRAILBOTTOMRIGHT;
	TRIPLERAIL;
	TARGET;
	CART;
	CARTONRAILVERTICAL;
	CARTONRAILHORIZONTAL;
	CARTONTURNINGRAILTOPLEFT;
	CARTONTURNINGRAILTOPRIGHT;
	CARTONTURNINGRAILBOTTOMLEFT;
	CARTONTURNINGRAILBOTTOMRIGHT;
	PLAYERONRAILVERTICAL;
	PLAYERONRAILHORIZONTAL;
	PLAYERONTURNINGRAILTOPLEFT;
	PLAYERONTURNINGRAILTOPRIGHT;
	PLAYERONTURNINGRAILBOTTOMLEFT;
	PLAYERONTURNINGRAILBOTTOMRIGHT;
	BOXONRAILVERTICAL;
	BOXONRAILHORIZONTAL;
	BOXONTURNINGRAILTOPLEFT;
	BOXONTURNINGRAILTOPRIGHT;
	BOXONTURNINGRAILBOTTOMLEFT;
	BOXONTURNINGRAILBOTTOMRIGHT;
	
}